### ISSUE TITLE
Slow deletion of bookmarks

### ISSUE THREAD

**Issue by cburkins** [xbrowsersync/app#152] opened 2020-01-24 01:37 UTC
**Describe the issue you are experiencing**
Every few days, I discover a bookmark is missing.

**How can the issue be reproduced?**
I very rarely delete bookmarks, so hoping there's some sort of log file (via API ?) that might show me any bookmarks deleted in the last few weeks.

**Screenshots**
None yet

**Desktop browser**
Chrome on Mac, Chrome on Windows, Firefox on Mac, Firefox on Windows.

 - OS: [e.g. Win10]
 - Browser [e.g. Chrome, Firefox]
 - Version [e.g. v1.5.0]

**Mobile device**
None

**Application log**
Please include the logs from the affected clients:
[xBrowserSyncLog_20200123203133388.txt](https://github.com/xbrowsersync/app/files/4106472/xBrowserSyncLog_20200123203133388.txt)

<details>
<summary>Log entries</summary>

```
Download the Application log from the Settings panel and paste the contents here.
```
</details>

**Comment by nero120** [comment] 2020-02-01 22:32
Couple of questions:

- Is there any relevant action that you perform that you can think of that consistently coincides with bookmarks going missing, e.g. opening your browser to find that the bookmark is suddenly gone, changing a sibling bookmark, etc.
- Do you move bookmarks around in Firefox using the bookmark manager window at all?

**Comment by cburkins** [comment] 2020-02-02 00:34
Hi Rich, thanks for replying, that was nice of you as I haven't been able to provide much good data for you yet.   I use xbrowsersync across three (or four ?) different computers to keep all my bookmarks in sync, using the same Sync ID for all.   Most of those browsers are Chrome, though I *might* be using Firefox in one case (I can look if that's relevant).   I do not manually reorganize my bookmarks (e.g. folders) on any of those machines, goes against my organizational philosophy :).   I use the bookmark search capability exclusively, never nagivating via folders.   In addition to xbrowsersync, I also use the Faux Bar Lite plugin on Chrome, as I like it's search interface.

**Comment by nero120** [comment] 2020-02-02 10:32
@cburkins thanks for the info. I've recently committed a number of updates that will hopefully improve the situation for both Firefox and Chrome, would you be willing to try the new release to see if it resolves any of your issues:

https://github.com/xbrowsersync/app/releases/tag/v1.5.1beta2

In Chrome, you'll need to enable Developer Mode in `chrome://extensions/`, then you should be able to drag the zip file to install the update. In Firefox, just drag the xpi file onto `about:addons`. As it's a beta it prevents you from using another other service except the test service, so jut create a new sync on there and restore your bookmarks from a backup of your main sync.

**Comment by cburkins** [comment] 2020-02-07 00:15
Do you think my issues stem from using the plugin within Firefox ?  If so,
I'm not a heavy firefox user, so I'm tempted to simply disable there.

**Comment by nero120** [comment] 2020-02-07 00:18
@cburkins it's definitely possible. If you could disable in Firefox and only use xBrowserSync on multiple Chrome browsers that would be a very good test - if the deletions stop then I know the problem is with Firefox. At the moment it's very difficult to nail down the issue as I cannot replicate it. 😢

**Comment by cburkins** [comment] 2020-02-07 19:12
Roger that, Rich.   Yup, I've removed from all Firefox configs, and will
let you know if I still see problems.    At the moment, it looks like I've
only got 176 bookmarks left.   Pretty sure it was alot more than that
before.   But hey, they're just bookmarks, right ?

I'm assuming that xBrowserSync doesn't have any long-term history on my
bookmarks ?

**Comment by nero120** [comment] 2020-02-07 19:30
@cburkins thanks, I appreciate it. If you restore from a previous backup then you can compare the total number.

**Comment by IssacEinstein** [comment] 2020-03-02 18:36
Deleting a Bookmark in Chrome is not being deleted in Android

**Comment by nero120** [comment] 2020-04-09 23:39
@cburkins [v1.5.2](https://github.com/xbrowsersync/app/releases/tag/v1.5.2) has now been released, can you please give it a try and report back if you're still experiencing the issue?

**Comment by cburkins** [comment] 2020-04-09 23:41
Thanks, will do so.  I will admit, so far, it very much feels like I'm
losing bookmarks, but that's anecdotal, as I can't provide specifics about
something that is missing :)

-Chad

**Comment by nero120** [comment] 2020-04-09 23:43
@cburkins one way you can observe this is to take a backup in xbrowsersync each day (Settings > Back up). You can then use a [diff checker](https://www.diffchecker.com/) to compare the backup files and see if bookmarks are indeed being lost.

**Comment by cburkins** [comment] 2020-04-09 23:45
Been hunting for an idea in this space, thanks !!

**Comment by nero120** [comment] 2020-04-29 14:30
@cburkins any updates on v1.5.2 so far, are you still losing bookmarks?

**Comment by IssacEinstein** [comment] 2020-04-29 14:35
hi., I'm worried about my bookmarks and stopped using that.
________________________________

**Comment by nero120** [comment] 2020-04-29 14:40
@IssacEinstein since v1.5.2 I am confident that these "deletion" issues have been all but resolved, I certainly have not had any further reports of deleted bookmarks since it's release. If you take a regular backup for a few weeks, just in case, after using xBrowserSync I'm sure you will see that your bookmarks are not being deleted any more.

**Comment by cburkins** [comment] 2020-04-29 18:29
Thanks for the tip on the built-in bookmark backup to JSON, have been
methodically checking for deleted bookmarks, and looks like we're good to
go, thanks for the hard work !

**Comment by IssacEinstein** [comment] 2020-04-29 18:32
And what i would suggest is to have a manual or automated backup process when ever u make changes to the bookmarks.
________________________________

**Comment by nero120** [comment] 2020-04-29 22:54
@cburkins that's fantastic news! Many thanks for checking and confirming this, I'll go ahead and close the issue.

@IssacEinstein that is probably overkill, however there is an existing feature request for [automatic backups](https://github.com/xbrowsersync/app/issues/15) that would provide enough resilience in case data corruption/deletion occurs again - I'll try and roll this into an upcoming release.

**Closed** 2020-04-29 22:54 UTC
Labels: needs triage

**Comment by cburkins** [comment] 2020-04-30 16:47
@nero120 Given that this is a free service, I don't have expectations of automatic backups.   you've got a unique capability setup here, and I'm grateful for it.    The manual backups that you already provide work just dandy for me.
