### ISSUE TITLE
Bookmarks corrupted when performing large amounts of changes

### ISSUE THREAD

**Issue by chronoviking** [xbrowsersync/app#75] opened 2019-02-04 20:14 UTC
I have had this multiple times and it is getting very frustrating.

Generally, when I bookmark a site, I just default to putting it in the Other Bookmarks folder so I can continue on my flow without having to file each and every site as I come across it. Then every few weeks I'll sort them into the correct folder.

However, once done, the xBrowserSync gets confused causing bad data to be synced to other machines. The corruption includes, but not limited to:
* Losing bookmarks
* Duplicating bookmarks
* Losing folders
* Duplicating folders

### Steps to reproduce
1. Have a set of bookmarks synced between at least two browser. All edits and updates will happen on only one browser.
2. In a folder, have about 20 bookmarks
3. (The following is just to simulate a large number of moves/edit)
4. In the folder, create five folders; A, E, I, O, and U
5. For each bookmark, edit the title to remove any numbers or punctuation
6. Move each bookmark into the subfolder of the first vowel in the title. So "xBrowserSync" would go in the "O" subfolder
7. Export to HTML the current bookmarks
8. Export bookmarks via xBrowserSync
9. Wait 15 minutes for syncing to occur
10. View bookmarks on second browser

### Expected behaviour
The bookmarks on the second device should match all the changes from the first device.

### Actual behaviour
The bookmarks on the second device are corrupted. If you compare the HTML exports to the xBrowserSync bookmarks, you will see differences already. Once the next sync happens, the corruption gets synced back to the original machine causing more issues.

### Client app information
**App Platform:** (Chrome, Firefox, iOS, etc) 
For my testing I used a single Windows 10 Pro machine, syncing between Firefox (where the changes occurred) and Chrome (the second browser)
**App Platform Version:** 

#### Other info
Possible culprits for the corruption:
* During an edit, the xBrowserSync notification is corrupted. So xBrowserSync records a change, but the record does not save correctly causes it to become unsynced with the current state of the bookmarks.
    * Perhaps a queue could be added so that when changes are made, they don't immediately try to update the xBS database, but instead to them in chunks when timing is not a factor
* A sync is happening while the edits are happening and xBrowserSync is trying to merge in the old bookmarks compared to the new edits
    * This could be solved by not allowing syncs if an update has happened in the last x seconds. This would give xBS time to solidify the changes before trying to merge.

**Comment by nero120** [comment] 2019-02-04 21:50
Hi @chronoviking, sorry about the issues you are having. You're not the only one to mention about corruption of syncs in certain cases but I'm unable to replicate the issue and so cannot find the cause of the issue.

What I need is a reproducible case using a specific data set and steps to reproduce. You've given me your steps above (which unfortunately did not reproduce the issue with my test or live data), would you be willing to provide me with an xBrowserSync backup file which gets you to a state where I will be able to reproduce the issue? If so please email it to admin@xbrowsersync.org with any extra steps required to reproduce the issue (if different to the above) and I'll get to the bottom of this.

Apologies again and many thanks for your assistance with this. 🙏 🙇 😃

**Comment by nero120** [comment] 2019-03-19 12:03
@chronoviking I've made some major updates to the syncing logic for the upcoming release which I hope will resolve all of your syncing issues. If you can spare a few moments, please give the [v1.5.0 beta release](https://github.com/xbrowsersync/app/releases/tag/v1.5.0beta) a try. It would be amazing if you can confirm whether or not it resolves your issues. 🙏

**Comment by urcindalo** [comment] 2019-03-27 10:00
I have also seen the issues reported by @chronoviking
The first two screenshots belong to the browser I used to tidy up by bookmarks, which were then sync'ed.
The last two ones were taken on another box, after sync'ing the changes. You can see the mistakes/corruption caused by the current stable version of xBrowserSync.

![LabFirefox_1](https://user-images.githubusercontent.com/87512/55066828-e0da1200-507e-11e9-8597-7167eb949362.png)
![LabFirefox_2](https://user-images.githubusercontent.com/87512/55066955-20a0f980-507f-11e9-843f-48a870f2a1ea.png)
![WinFirefox_1](https://user-images.githubusercontent.com/87512/55067105-6362d180-507f-11e9-876a-2e9b42c95e34.png)
![WinFirefox_2](https://user-images.githubusercontent.com/87512/55067111-69f14900-507f-11e9-955c-07aef3939f00.png)

**Comment by nero120** [comment] 2019-03-27 14:44
@urcindalo which browser is that (and version)?

Would you be able to try the [beta](https://github.com/xbrowsersync/app/releases/tag/v1.5.0beta) and see if it resolves your issues?

**Comment by urcindalo** [comment] 2019-03-27 18:11
Official Firefox in both cases.
a) First two screenshots: v60.5.2 on Linux 64 (Gentoo).
b) Last two ones: latest version (66.x, I don't recall right now) on Windows 7 64.

What should I do to try the beta? Create a new Sync ID, just in case?

**Comment by nero120** [comment] 2019-03-28 07:52
> Official Firefox in both cases.

Ok that's fine, just wanted to check.

> What should I do to try the beta? Create a new Sync ID, just in case?

To avoid affecting your current data, create a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) in Firefox, start Firefox using that new profile then install the beta. Yes I'd recommend creating a new sync ID in the beta and using that for your testing.

**Comment by urcindalo** [comment] 2019-03-28 10:50
OK. What I did:
1) On my "main" Firefox I created a new profile, launch FF with the new profile, logged into my FF account (I sync everything except bookmarks) and let it install all the extensions.
2) I logged with my xbrowsersync ID and updated the extension.
3) The new beta version forced me to log again. Instead of creating a new ID, I wanted to check whether the new beta version was able to correctly track the changes, so I logged in with my existing ID. As expected, the sync'ing left me with the messed-up version of my bookmarks (last two screenshots a few messages above).
4) I then tidied-up the boomarks in FF and let xbrowsersync do its job. However, it was taking forever to complete the sync (a bug?) so I quit FF and relaunch it: my bookmarks appeared immediately as sync'ed in xbrowsersync as soon as FF started and the bookmark structure seemed OK inside FF.
5) I the quit my "main" FF and opened my Windows FF in the Virtual Machine. Instead of creating a new profile, I wanted to know if just updating xbrowsersync to the new beta and letting it do its job would be enough to correctly detect my bookmarks subfolder structure. But, NO. I still get a messed-up version, although it correctly detected a new entry into the Invesiones subfolder that it had, however, incorrectly assigned to the Amazfit Bip subfolder.

If you look at my screenshots, the "Inversiones" subfolder is the 14th entry inside "Otros marcadores" folder. However, the 14th subfolder in the messed-up version of my bookmarks is "Amazfit Bip", which however contains the bookmarks from the good 14th Inversiones subfolder of the "main" FF.

Maybe there's a bug/problem in the way xbrowsersync detect folders or entries? Does it rely on their position instead of the name? Is it unable to detect that position 13th changed from a single entry to a subfolder, for instance? Just an idea.

**Comment by urcindalo** [comment] 2019-03-29 08:31
Update:
After going back to the "main" FF, the bookmarks were re-sync'ed again at start to the messed-up version. This time, when trying to move all of the bookmarks inside "Amazfit Bip" subfolder to "Inversiones", an error was displayed for a short time on screen, the bookmarks were re-sync'ed again (a had to wait a little), and the messed-up version was brought back... but this time two of the URLs were in the right subfolder. This made me think that, maybe, I should move them one by one, in single steps.
So, I just moved them one at a time, waiting for the icon to display the change was sync'ed before proceeding with the next one. By doing so, no errors were displayed.
Now, I'm home on a third FF (also on Linux) which still has the stable xbrowsersync version and, to my surprise, the sync process ran as expected: I now see all of the bookmarks in their proper subfolders and no single one is outside a subfolder.

**Comment by nero120** [comment] 2019-03-29 09:20
Interesting thank you @urcindalo, that is very useful information. Are you able to download the log files and email them to admin@xbrowsersync.org?

> Instead of creating a new ID, I wanted to check whether the new beta version was able to correctly track the changes, so I logged in with my existing ID. As expected, the sync'ing left me with the messed-up version of my bookmarks.

Just to say this is as expected, when the corruption occurs it is likely corrupting the synced data and pushed to the cloud, which means the corruption would be replicated locally when you re-synced to this ID using the beta.

I believe the issue is that in certain circumstances, when a user makes changes using the browser's bookmark manager xBrowserSync does not select the correct corresponding synced bookmark to the local bookmark that the change was made to. I have a plan to remedy this, if you are able to send me the log files it may help in confirming the issue. 🙏

**Comment by urcindalo** [comment] 2019-03-29 10:26
OK. This first one comes from the profile in the "main" FF for which, yesterday, I update the extension form stable to beta. The synced data in the cloud was already good, so nothing really here, I guess.
[xBrowserSyncLog_20190329103351093.txt](https://github.com/xbrowsersync/app/files/3022166/xBrowserSyncLog_20190329103351093.txt)

**Comment by urcindalo** [comment] 2019-03-29 10:30
This one comes from the Windows FF for which I also updated yesterday the extension from stable to beta without changing the user profile. This FF instance still had a messed-up bookmarks version from yesterday which, upon sync'ing a few moments ago, is now OK.
[xBrowserSyncLog_20190329105318993.txt](https://github.com/xbrowsersync/app/files/3022175/xBrowserSyncLog_20190329105318993.txt)

**Comment by urcindalo** [comment] 2019-03-29 10:40
But, now, this is VERY interesting, I guess.
Since on my "main" FF with the yesterday-newly-created-test profile everything seems to be OK, I've decided to launch this "main" FF with my *regular* user profile (identical to the one I created yesterday since my FF user account took care of it). In this regular profile, I updated the stable xBrwoserSync to the beta version (exactly as I did yesterday in the test profile). So, the new beta version in the regular profile forces me to re-login. OK, I enter my sync ID and password, it begins sync'ing AND THEN FAILS. I tried this several times, even de-installing and re-installing the extension, just in case. Everytime I use the *stable* version, it syncs OK, but when I use the beta version, the sync error in the log occurs.
It surprises me updating from stable to beta worked yesterday in two different FF's but today it fails on the same "main" FF where it worked yesterday on a test profile.
[xBrowserSyncLog_20190329111934164.txt](https://github.com/xbrowsersync/app/files/3022181/xBrowserSyncLog_20190329111934164.txt)

**Comment by urcindalo** [comment] 2019-03-29 10:42
I use also Chrome and the stable xBrowserSync has been able to correctly update today my boomarks to the good ones. However, I can't provide a log since I can't update from stable to beta on it (as you know).

**Comment by nero120** [comment] 2019-03-29 11:00
> But, now, this is VERY interesting, I guess.

That is very strange, the error in the log is surprising. Are you willing to send me an xbs backup of your bookmarks so I can debug this locally? If so you can email to admin@xbrowsersync.org.

**Comment by urcindalo** [comment] 2019-03-29 11:29
Sure!
Done.

**Comment by urcindalo** [comment] 2019-03-29 12:32
The same just happened on a different box. I've had to revert xBrowserSync back to the stable version.
[xBrowserSyncLog_20190329132219111.txt](https://github.com/xbrowsersync/app/files/3022622/xBrowserSyncLog_20190329132219111.txt)

**Comment by nero120** [comment] 2019-06-03 17:51
Please try again using the latest [beta](https://github.com/xbrowsersync/app/releases/tag/v1.5.0beta). I've included more logging and [raised a bug with Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1556427) that affects moving or deleting multiple bookmarks simultaneously which could be a potential source of your issues.

If you do experience the issue again, please attach the xBrowserSync logs from all affected browsers.

**Comment by nero120** [comment] 2019-06-27 21:36
@chronoviking would you mind trying the latest [v1.5.0beta11](https://github.com/xbrowsersync/app/releases/tag/v1.5.0beta)?

Please be aware however, due to a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1556427) in Firefox's bookmarks API, changing multiple bookmarks simultaneously will likely result in an error in xBrowserSync. The issues has been fixed in the latest [Firefox Nightly (v69.0a1)](https://www.mozilla.org/en-US/firefox/nightly/all/) so please download and test with Nightly so that you don't hit that known issue.

**Comment by nero120** [comment] 2019-08-01 09:54
@chronoviking @urcindalo I've just released [v1.5.0](https://github.com/xbrowsersync/app/releases/tag/v1.5.0) which resolves most syncing issues, however there are [known issues](https://github.com/xbrowsersync/app/wiki/Known-issues) in Firefox due to bug's in Firefox's bookmarks API which can cause changes to be missed when performing many changes or simultaneous changes.

Unfortunately there's not much we can do until Mozilla fixes these issues. I am tracking the relevant bugs (e.g. 1556427](https://bugzilla.mozilla.org/show_bug.cgi?id=1556427)) and will keep the pressure on Mozilla to resolve them asap.

**Closed by nero120** 2019-08-01 09:54 UTC
Labels: bug, on hold
