### ISSUE TITLE
Firefox addon does not remember login credentials on browser restart

### ISSUE THREAD

**Issue by kaphula** [xbrowsersync/app#95] opened 2019-05-02 13:30 UTC
xbrowsersync does not remember login credentials between browser sessions. Each time I close Firefox and open it again the xbrowsersync requires me to login to it using sync ID and password.

### Client app information
**App Platform:** Firefox 66.0.3 (64-bit), Manjaro Linux

**App Platform Version:** 1.4.0

**Comment by nero120** [comment] 2019-05-02 13:41
Hi @kaphula, this is a duplicate of #38. It has been fixed and will be released in the upcoming release (v1.5.0).

**Closed by nero120** 2019-05-02 13:41 UTC
