### ISSUE TITLE
Selective Sync

### ISSUE THREAD

**Issue by emale999** [xbrowsersync/app#232] opened 2020-08-26 19:11 UTC
Select Bookmarks folders that shouldn't sync to other browsers.
This should be combined with another feature request to merge (and not delete) bookmarks

**Comment by nero120** [comment] 2020-09-07 09:19
Hi @emale999, this is essentially a duplicate of #26 and #194 so please upvote (or comment on) those.

**Closed by nero120** 2020-09-07 09:19 UTC
