### ISSUE TITLE
Sync is broken "Connection to service lost. Check your network connection and try again."

### ISSUE THREAD

**Issue by ioogithub** [xbrowsersync/app#428] opened 2022-10-29 04:59 UTC
**Describe the issue you are experiencing**
Sync is broken. When the android app is opened an error message is displayed "Connection to service lost. Check your network connection and try again."

**How can the issue be reproduced?**

1. Open Android App
2. Observe that app is not syncing and there is a red error message on the bottom.

**Desktop browser**
Please complete the following information for all affected desktop browsers:

- OS: Android
- Browser n/a I am using the Android app.
- Version 1.5.2

**Mobile device**
Please complete the following information for all affected mobile devices:

- Device: Redmi Note 10
- OS: Android 11
- Version 1.5.2

**Application log**
Please include the logs from the affected clients:

`
2022-10-29 04:52:34.980	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2532:42 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
`

This error is repeated over and over.

**Comment by ThePhoDit** [comment] 2022-10-30 21:02
This is happening to me too on FireFox so I guess it is an error of the official API, not the app. It has been several days with it randomly going off and back.

**Comment by nero120** [comment] 2022-10-31 14:29
Duplicate of #426

**Closed by nero120** 2022-10-31 14:29 UTC
