### ISSUE TITLE
Bookmarks becoming folders

### ISSUE THREAD

**Issue by SpearheadUK** [xBrowserSync/App#36] opened 2018-09-11 08:14 UTC
### Steps to reproduce
1. create new bookmark
2. close browser
3. open new browser
3. sync takes place
5. some of new bookmarks are changes to folders with the same name

### Expected behaviour
sync should update browser with all new bookmarks

### Actual behaviour
some new bookmarks become folders and link is lost

### Client app information
**App Platform:** (Chrome, Firefox, iOS, etc) Firefox 62

**App Platform Version:** xbrowsersync 1.4.0 (updated 6th september 2018)

#### Other info
Not sure if there is something specific to the links that cause this but seems to always affect the same bookmarks.

**Comment by nero120** [comment] 2018-09-11 12:32
Thanks @SpearheadUK, so you're adding it using the bookmark "star" right?

![image](https://user-images.githubusercontent.com/4236238/45360135-943d5680-b5c6-11e8-87cb-4779e39142dc.png)

That should be fine, I've just tested adding the bookmark in the same way in Firefox on one PC and my second PC running Firefox + XBS beta has automatically synced the change. I've not noticed any other bookmarks being "corrupted" (changing into a folder), can you give me some more info on which bookmarks were being corrupted in this way?

Also, importantly, if you disable sync on both PCs (Settings > Disable Sync) then re-enable the sync:

1. Does this resolve the issue (do the folders turn back into bookmarks? And,
2. Are all of the bookmarks identical on both PCs?

**Comment by crankynet** [comment] 2018-09-11 16:29
@SpearheadUK, I ran into a similar issue with the 1st beta but did not run beta 2 long enough to see this issue. Was Chrome the browser in step 2 and FF for step 3? What happens if you re-open the browser you closed in step 2? Dd the folder bookmarks get push to it?

**Comment by SpearheadUK** [comment] 2018-09-11 19:36
I do have the extension installed on a copy of chrome. But I rarely use it. I believe I have experience this issue without any syncing taking place with chrome.

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by crankynet** [comment] 2018-09-15 05:59
I ran into the same issue when I run Virtualbox Windows 10 with latest Chrom & Firefox+ XBS.
1) Verify bookmark set on both Chrome & FF are identical.
2) close FF
3) Add a bookmark on Chrome (not sure this is the issue)
4) Start FF again.
5) Bookmark sync takes place and one of the bookmark becomes a folder.
![snap735](https://user-images.githubusercontent.com/41879315/45583162-ac84ce00-b871-11e8-8c9f-c08076fd9be4.jpg)

**Comment by crankynet** [comment] 2018-09-15 06:02
One more point to add:
The CNN bookmark changes to a folder on FF first and the one on Chrome changes soon after.

**Comment by nero120** [comment] 2018-09-15 06:07
@crankynet could you just confirm for me, if you disable then re-enable the sync on Firefox (without changing any bookmarks), so you notice any odd changes? And if you do this multiple times do you notice anything?

I'm trying to determine if it's the re-population logic that is causing the problem.

**Comment by crankynet** [comment] 2018-09-15 13:43
Have disable/enable multiple times without issue but...
WIth XBS enabled on both, I renamed one of the bookmarks on FF (Lifehacker). Eventually, resync took place on Chrome and "Lifehacker" is changed to a folder. Seems like re-population is not causing the problem.

![snap742](https://user-images.githubusercontent.com/41879315/45586896-a531e480-b8b2-11e8-942f-830f8843f67f.jpg)

**Comment by crankynet** [comment] 2018-09-15 13:59
It has been more than 15 minutes since the last sync on Chrome, the Lifehacker bookmark on FF is still showing as a bookmark and the one on Chrome is still a folder.

**Comment by crankynet** [comment] 2018-09-15 14:39
Rename another bookmark on Chrome and Lifehacker became a folder on FF after resync.

**Comment by crankynet** [comment] 2018-09-15 15:27
I have not done much testing but I think bookmark to folder only happen to bookmarks on the bookmark bar, don't recall it ever happened to bookmarks in any folder.

**Comment by SpearheadUK** [comment] 2018-09-15 18:06
I can't test right now as I'm away. But I have never had it to bookmark bar items. It's probably some random corruption. Could it happen if the url is lost from the bookmark?

________________________________

**Comment by crankynet** [comment] 2018-09-15 18:13
Maybe you are on to something. XBS got the name of the bookmark from the server but the URL is not valid. WIth XBS can't recreate the bookmark, it wipes the URL field and the bookmark becomes a "folder"?

**Comment by nero120** [comment] 2018-09-17 16:30
Just to let you both know, I've managed to recreate this issue and I know what the cause is. It will occur whenever you use Firefox's native bookmarks functionality to rename a bookmark (in any location), and is caused by the fact that Mozilla only provide the changed info (i.e. just the title) in the triggered event as opposed to the entire bookmark object.

Will get this fixed asap, thanks for both your help with pinning this one down guys. 👍

**Comment by crankynet** [comment] 2018-09-17 16:32
Great news. Thanks.

**Comment by crankynet** [comment] 2018-09-17 16:38
At least for the Beta, maybe the sync check should be every 5 minutes or so just so we can see if there is any issues? 10 or 15 minutes is fine for regular use.

**Comment by nero120** [comment] 2018-09-17 16:49
> At least for the Beta, maybe the sync check should be every 5 minutes or so just so we can see if there is any issues? 10 or 15 minutes is fine for regular use.

Yes that is a good idea, I had to make it more frequent to debug the issue so I'll commit the fix with this change to help future testing.

**Comment by SpearheadUK** [comment] 2018-09-17 16:56
Great to hear.

________________________________

**Comment by nero120** [comment] 2018-09-19 10:30
Hi guys, grab the [latest builds](https://github.com/xBrowserSync/App/releases/tag/BETA1) which should have resolved this issue. If you could confirm this has been fixed (or not) I would greatly appreciate it!

**Comment by crankynet** [comment] 2018-09-19 14:35
Installed the latest build on both Firefox & Chrom. As far as I can tell, XBS on FF is running fine but it was disconnected on Chome after maybe 10 or 15 minutes. After reconnection, the bookmarks don't look the same. 1st screenshot is from FF, 2nd and 3rd one are from Chrome.
![snap725](https://user-images.githubusercontent.com/41879315/45760291-931bb300-bbde-11e8-914b-5d8e84dd5743.jpg)

![snap726](https://user-images.githubusercontent.com/41879315/45760311-9adb5780-bbde-11e8-9d19-99e256aa9839.jpg)

![snap727](https://user-images.githubusercontent.com/41879315/45760325-9fa00b80-bbde-11e8-9c72-79be40b75f60.jpg)

**Comment by nero120** [comment] 2018-09-19 14:49
@crankynet that looks correct to me - all of the bookmarks are where they should be. The only difference is "Recent Tags", but Chrome does not implement these types of FF-specific pseudo-bookmarks (that use a `place:` prefix, e.g. for Recent Tags: `place:type=6&sort=14&maxResults=10`) so you won't see a submenu of this one in Chrome.

**Comment by crankynet** [comment] 2018-09-19 14:57
The issue I see is the "other bookmarks" of FF is stored under "other bookmarks" -> "[xbs] Menu" on Chrome.

**Comment by nero120** [comment] 2018-09-19 15:20
If you open `Other Bookmarks` in FF

![image](https://user-images.githubusercontent.com/4236238/45762346-19a7b300-bc26-11e8-8b27-84e33db4bded.png)

I reckon you will see `Dictionary.com` and `Lifehacker` as per Chrome:

![image](https://user-images.githubusercontent.com/4236238/45762209-c46ba180-bc25-11e8-9335-7a478e42553f.png)

If that's the case then `Other Bookmarks` is syncing to the correct place on both browsers. The confusion arises because although both browsers have `Other Bookmarks` and `Bookmarks Toolbar`, only FF has the concept of a `Bookmarks Menu` (and it also has `Mobile Bookmarks` but that isn't relevant here). Because Chrome does not have a `Bookmarks Menu` container, these bookmarks need to be synced to a folder within `Other Bookmarks` (which is named `[xbs] Menu`) instead.

It's easier to visualise using the Bookmarks Library window in FF:

![image](https://user-images.githubusercontent.com/4236238/45762869-3f818780-bc27-11e8-8f30-c9c2ef86bca5.png)

So in your case, the contents of `Bookmarks Menu` is

![image](https://user-images.githubusercontent.com/4236238/45763072-a868ff80-bc27-11e8-8336-9dc43958ce8a.png)

which is exactly what appears in Chrome's `Other Bookmarks` > `[xbs] Menu`

![image](https://user-images.githubusercontent.com/4236238/45763121-bf0f5680-bc27-11e8-8821-cb2d11035bca.png)

Sorry for the wordy response, hope that clears things up!

**Comment by crankynet** [comment] 2018-09-20 04:45
Add a bookmark under "other bookmarks" on Chrome and the bookmark ended up in "Other Bookmarks"-> [xbs]Unfiled on FF. Delete the [xbs] unfiled folder but got disconnection from the server.

![snap729](https://user-images.githubusercontent.com/41879315/45796400-33acba00-bc55-11e8-8b08-15edc9a9b28c.jpg)

**Comment by nero120** [comment] 2018-09-20 08:38
Yes that's how it currently works, the `[xbs]...` folders are containers so they can't be deleted, if you try xBrowserSync will disable your sync and show the above alert.

However this has got me thinking, by default when you add a bookmark using the xBrowserSync extension window, the bookmark is placed in the `Other Bookmarks` > `[xbs] Unfiled` folder. It might be better to add the bookmark directly into `Other Bookmarks` than placing them into a subfolder (and a future enhancement could allow the user to set where the bookmarks are added by default). What do you think?

**Comment by crankynet** [comment] 2018-09-20 14:55
Not sure if this is new...
Add a bookmark to "other bookmarks" on Chrome using keyboard shortcut control-d, and sync is disabled a few seconds later (or right away but not sure). My bookmark set is 182k according to the 1.3.1 version of the extension.

**Comment by nero120** [comment] 2018-09-20 15:29
@crankynet adding a bookmark won't disable your sync on it's own, try it with a new sync to compare - create a new Chrome profile (which will have no bookmarks), add xBrowserSync, and create a new sync. Then try adding your bookmark. If it succeeds then it could be some corruption in your sync data which is causing the issue, like with [this issue](https://github.com/xBrowserSync/App/issues/37).

**Comment by nero120** [comment] 2018-09-20 15:31
Anyway, it looks like the original reported issue has been resolved so I'm going to close this now.

**Closed by nero120** 2018-09-20 15:31 UTC
Labels: bug
