### ISSUE TITLE
[v1.4.0 BETA] Not syncing between FF on 2 PCs

### ISSUE THREAD

**Issue by crankynet** [xBrowserSync/App#33] opened 2018-08-06 17:03 UTC
### Steps to reproduce
1. Install xBS 1.4 Beta on PC 1 and create sync ID
2. Let it run 1+ hrs.
3. Install xBS 1.4 beta on PC 2 and set it up with sync ID from PC 1
4. Click OK to overwrite local bookmarks when prompte

### Expected behaviour
Bookmarks on PC 2's FF should be identical to PC1's FF.

### Actual behaviour
Bookmarks are not the same between PC 1 & PC 2.

### Client app information
Both PC run FF 61.0.1 (64 bit) under Windows 10 x64. 

**App Platform Version:** `

**Comment by crankynet** [comment] 2018-08-06 20:41
Did another test.
1. Disable sync on PC 1.
2. Re-enable syn on PC 1 by enter the password.
3. Click OK to overwrite local bookmarks.
After sync, duplicated bookmarks can be seen at the beginning of bookmark bar & under "other bookmarks". At least for the bookmark bar bookmarks, the added bookmarks are random while the existing ones are in the right order.
Let say I have bookmark a, b, c d & e be,fore sync. After sync, I get c, b, a, d, e, a, b, c,  d & e.

**Comment by nero120** [comment] 2018-08-08 21:11
Hi @crankynet, I've tried to re-create your issue across two machines running Firefox 61.0.1 (one Windows 10 and the other Ubuntu 16.04.5 LTS, both x64) but I've not been successful. I created a new sync ID on Ubuntu and added 3 bookmarks (by using the xBrowserSync popup and the native add bookmark button). Then, I synced to this ID on the Windows machine and the three bookmarks came across in the correct folder and in the correct order.

I've also tried disabling/re-enabling syncs but each time the bookmarks re-appear in the correct order.

Can I check the following with you:

- Are you definitely running the **latest** beta from the [release page](https://github.com/xBrowserSync/App/releases/tag/BETA1)?
- Do you have the "Include bookmarks bar" setting disabled on either/both machines?
- Are you getting any errors when syncing when [debugging](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Debugging) the extension?
- Can you email the sync ID and password to admin@xbrowsersync.org so I can try to re-create the issue?

**Comment by crankynet** [comment] 2018-08-08 21:48
Are you definitely running the latest beta from the release page?
  I downloaded it a few days ago. Installed it on one PC by itself until couple of days ago. Installed the same XPI on the 2nd PC and noticed the issue.

Do you have the "Include bookmarks bar" setting disabled on either/both machines?
 "include bookmarks" should not be enabled? Both PCs have it enabled.

Are you getting any errors when syncing when debugging the extension?
  did not see any error.

Can you email the sync ID and password to admin@xbrowsersync.org so I can try to re-create the issue?
  Sorry, rather not share my bookmarks with anyone. I have about 30 to 40 bookmarks on my bookmark bar and over 20 folders under "other bookmarks".

I did use FireFox account to sync bookmarks but I logged out before install xBS.

**Comment by nero120** [comment] 2018-08-08 22:14
Ok then would you be able to perform the following test for me:

1. Sync to your existing sync ID if you are not already synced.
2. Hit `ctrl+shift+b` to open the bookmarks library window and check all of your bookmarks are present, take some screenshots to remember the order.
3. Disable your sync, then delete all of the existing bookmarks in the library window (if you're concerned about losing them then use Firefox's backup bookmarks functionality first). Your library should now be empty with nothing inside Bookmarks Toolbar, Bookmarks Menu, and Other Bookmarks.
4. Re-enable your sync which will re-populate the bookmarks library with your synced bookmarks. Once synced, check the library against your screenshots and describe any differences you see here. Note: you can sort bookmarks in the library which can affect the order so ensure you are not currently sorting (there should be no arrow against the headings Name, Tags, Location, etc).

**Comment by crankynet** [comment] 2018-08-09 05:18
By deleting the local bookmarks, I do get the correct bookmarks from the xBS server. Maybe xBS should clear all local bookmarks when a user is enabling sync with an existing sync ID?

**Comment by crankynet** [comment] 2018-08-09 05:30
After I deleted local bookmarks and used the same sync ID on my 2nd PC, the 2nd bookmark on my bookmark bar is added to the end of the bookmarks bar. As far as I can tell, everything else is OK.

**Comment by nero120** [comment] 2018-08-09 08:32
Interesting! So xbs does clear the local bookmarks before populating but after your last response I did some further testing and it looks like there is indeed a bug where the populating begins before the clearing down is finished. It's likely that this is the cause of your issues so leave it with me and I'll get this resolved, then upload a new beta build for you to try. Thanks for raising this!

**Comment by crankynet** [comment] 2018-08-09 15:16
After both PCs were powered down for the night, powered up PC 1 this morning and noticed the 1st bookmark is missing from the bookmark bar. Added it back and renamed one of the bookmark on the bookmark bar. Left the PC on for 1+ hrs. Powered it down and powered up the PC 2. xbs updated the bookmarks on PC 2 but the 1st bookmark is again missing from the bookmark bar.

**Comment by nero120** [comment] 2018-08-09 16:23
Hi @crankynet, I'm finding it difficult to recreate these issues so could you give me a step by step process of exactly how to reproduce the issues that you're finding? FF syncing for me is working perfectly so clearly something is causing your setup not to function as it should, but if I can't reproduce it I can't fix it.

Also, could you please ensure that you enable debugging of the extension by following [this](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Debugging) guide. I really need to know if there are any errors occurring which could be causing these issues, they would be logged to the console when you're debugging so please also post any console errors here as well. Thanks!

**Comment by crankynet** [comment] 2018-08-09 17:33
Powered up PC 1 after PC 2 has been running for 2+ hrs and noticed the bookmark bars are different between the 2. The 2nd bookmark (www.google.com witth name Ggle) was changed to a folder with nothing in it. The name was changed from Ggle to .. which was what I used until last night.
[xBS debug log.txt](https://github.com/xBrowserSync/App/files/2275230/xBS.debug.log.txt)
![pc 1 bookmark bar](https://user-images.githubusercontent.com/41879315/43915336-41e8adba-9bbf-11e8-9ea2-e33b9115271f.jpg)
![pc 2 bookmark bar](https://user-images.githubusercontent.com/41879315/43915340-433af498-9bbf-11e8-8ad6-f97950646b73.jpg)

**Comment by crankynet** [comment] 2018-08-09 20:08
I powered up PC 1 few minutes ago while PC 2 is still on. Decided to move back to Firefox sync for now. I may be able to try again when you have another build.

**Comment by nero120** [comment] 2018-08-10 10:27
Thanks for this info @crankynet. From the attached log it doesn't look like there are any errors occurring with xbs whilst you are syncing. I'll do some more testing and see if I can find the cause.

**Comment by nero120** [comment] 2018-08-10 10:47
Actually I just had a thought, perhaps this might explain the difference. Xbs checks for updates to your synced bookmarks every 15 minutes (in the background), if it discovers your synced bookmarks have changed then it updates your local bookmarks accordingly. It also checks for updates when FF is "started up" (according to [Mozilla](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onStartup), this is when _"a profile that has this extension installed first starts up. This event is not fired when a private browsing/incognito profile is started, even if this extension is operating in 'split' incognito mode."_)

> Powered up PC 1 after PC 2 has been running for 2+ hrs and noticed the bookmark bars are different between the 2. The 2nd bookmark (www.google.com witth name Ggle) was changed to a folder with nothing in it. The name was changed from Ggle to .. which was what I used until last night.

So, given what I stated above, if when you started up PC 1 FF was already running (perhaps started from sleep or hibernate mode?) you would have had to wait 15 minutes before xbs checked for updates and updated local bookmarks, which may explain the difference you saw in the bookmarks bar on PC 1.

So there's a couple of questions/issues to clarify here:

1. When syncing, does xbs create local bookmarks exactly in number and order as per the synced bookmarks?
2. Is there an issue with xbs automatically checking for updates?

As for (1), you can test this by repeatedly disabling and re-enabling sync (on the same machine). After you re-enable sync each time your local bookmarks should look exactly the same, there should definitely be no difference in number or order of bookmarks, if there is then there is definitely a bug in the bookmark population code. (Note: I have tested this extensively and have not been able to find any issues like this)

For (2), when you've updated bookmarks on one PC then you have to give the other at least 15 minutes before those changes will be picked up and synced on the other PC, after that point the local bookmarks should be identical on both (assuming you didn't manually make any changes to bookmarks in that time).

I'd really appreciate to hear your thoughts in light of this and if you'd be willing to try my suggestions out to see if it resolves the issues you're seeing.

**Comment by nero120** [comment] 2018-09-05 14:34
@crankynet I've just committed a fix for #34 which I believe may resolve some of your issues here. I've uploaded new builds to the [beta release](https://github.com/xBrowserSync/App/releases/tag/BETA1) page which include the fix, if you're willing to give it another try hopefully you'll have better luck.

**Comment by crankynet** [comment] 2018-09-05 15:48
Installed FF xsync beta on PC 1 at 8 AM with a new sync ID, put PC1 to sleep and install beta on PC 2 at 8:30 AM without deleting any local bookmarks. Xsync is able to wipe the local bookmarks and populate with bookmarks from the server correctly as far as I can tell.  Will use PC2 most of today but will take PC1 out of sleep later this evening to see if I run into any issues.

**Comment by crankynet** [comment] 2018-09-05 22:50
Ran into 2 abnormalities so far.
1) Placed PC2 to sleep and took it to a public WiFi place. Resumed and noticed the 1st bookmark of the bookmarks toolbar is missing. Manually added it back to the toolbar and it has been OK.
2) After about an hour, took PC2 back to home WiFi and noticed the 2nd bookmark from the toolbar has moved to the end of the toolbar.
As far as I can tell, the bookmarks in folders are OK but I did not check many of them.

**Comment by crankynet** [comment] 2018-09-06 03:27
Found 2 more abnormalities when I took PC1 out of sleep:
1) Place PC2 to sleep, took PC1 out of sleep.
2) xsb detects bookmarks have been changed and did a sync after about 8 minutes.
3) After sync, the last bookmark on the bookmarks bar is gone and the 1st bookmark on the bookmarks bar is inserted to the 3rd position but the 1st bookmark is not removed.

**Comment by crankynet** [comment] 2018-09-06 03:30
Will go back to FF sync...

**Comment by nero120** [comment] 2018-09-06 03:35
@crankynet can you do this for me please as no one else is reporting these issues:

1. Start PC1, disable then re-enable your sync.
2. Start PC2, disable then re-enable your sync.

**Do not change any bookmarks manually.** Now, are the bookmarks identical on both machines and can you confirm that the sync ID is the same for both machines?

**Comment by crankynet** [comment] 2018-09-06 03:45
I am sorry, I have removed xbs beta 2 because there ware more corruptions with the bookmarks on the bookmarks toolbar after my last post. Seems like the errors I saw are not that difficult to duplicate.

**Comment by nero120** [comment] 2018-09-06 03:46
Really helpful, thanks very much.

**Closed by nero120** 2018-09-06 03:46 UTC
Labels: bug

**Comment by crankynet** [comment] 2018-09-06 03:53
Will try again if there is a new beta or final release. Thanks.

**Comment by nero120** [comment] 2018-09-19 11:26
@crankynet I've [uploaded new builds (v1.4.0 c)](https://github.com/xBrowserSync/App/releases/tag/BETA1) which have fixed a number of sync issues, might be worth a try.

I have not been able to replicate the issue of synced bookmarks not being the same/out of order so hopefully the underlying issue has been resolved?
