### ISSUE TITLE
Extension keeps getting disabled.

### ISSUE THREAD

**Issue by rfmsec** [xBrowserSync/App#37] opened 2018-09-16 21:03 UTC
### Steps to reproduce
1. Create a sync profile
2. Add another browser (I'm using 1. chrome browser and 2. firefox browsers) 
3. Once all browsers are synced, add a bookmark on one of the browsers.

### Expected behaviour
Bookmark should be added to the profile and later synced to the other browsers.

### Actual behaviour
The browser where the new bookmark is added is getting out of sync, sync gets disabled, and I'm creating a local backup, login again and restore from the backup.
Later I need to restore the backup on all of the other browsers as well.

### Client app information
**App Platform:** (Chrome, Firefox, iOS, etc) 
Chrome and Firefox

**App Platform Version:** 
1.4

**Comment by rfmsec** [comment] 2018-09-16 21:06
I wanted to take the opportunity to thank you for your support and the addon itself, I personally think that this is a great piece of work and I'm looking forward to future versions to see how it develops.

**Comment by nero120** [comment] 2018-09-17 09:04
Thanks for the kind words @rfmsec!

Regarding the issue you're having, there was an issue in the v1.4.0 beta where the automatic update checks were not happening. This was fixed about two weeks ago so if you downloaded the beta before the 5th Sept please go ahead and get the [latest version](https://github.com/xBrowserSync/App/releases/tag/BETA1) and give it another try.

Otherwise, each browser that is synced to the same sync ID will automatically check for updates every 15 minutes, so the process should work as follows (for both Chrome and Firefox):

1. Sync every browser to the same sync ID.
2. Add/remove/change a bookmark on browser 1, change is synced.
3. Wait up to 15 minutes.
4. Browsers 2, 3, 4, etc will check for updates automatically and sync the latest change.

Note that if you change a bookmark on any browser other than 1 **before** the automatic update check has occurred then you will get the "Data out of sync" warning and the sync will be disabled. This is because xBrowserSync does not currently support push changes and so won't be able to deal with sync conflicts where you are making changes to two browsers (synced to the same ID) at around the same time.

If in spite of all this, you still think there is an issue, please confirm and I'll look into it again.

**Comment by rfmsec** [comment] 2018-09-17 09:10
Hi @nero120,

I have installed the latest version of the addons prior to opening the issue :)
I can confirm that changes are being made, are not within 15 minutes.

Yesterday, I've added a new bookmark after several days, this caused the "Data out of sync" issue to recur.

I can try and open a new Sync profile and see if there is an issue with my profile if you suggest it.

Thanks,
Waiting for your response.

**Comment by nero120** [comment] 2018-09-17 09:18
Ok no worries @rfmsec I'll look into it.

Can you tell me which browser did you get the out of sync message on, Chrome or Firefox?

**Comment by nero120** [comment] 2018-09-18 09:39
@rfmsec ah so the "xBrowserSync folder changed" error is actually a different one to "Data out of sync". Can you tell me are you seeing both errors or just "xBrowserSync folder changed"? Also, are you able to provide me with a step by step to replicate the issue (Open Firefox, go to www...., click on xBrowserSync icon, etc)?

**Comment by nero120** [comment] 2018-09-19 10:32
@rfmsec I've [uploaded new builds](https://github.com/xBrowserSync/App/releases/tag/BETA1) which have fixed a number of sync issues, please could you install them and see if this issue has been resolved?

**Comment by rfmsec** [comment] 2018-09-19 20:10
@nero120,
I did see the "Data out of sync" error so it was in my top of mind, but the error I usually see is the Folder Changed error...

Steps to reproduce the issue:

Open chrome
Add a few bookmarks
Create a sync profile

Open firefox
Use the same profile ID

Wait 15 minutes, not to cause Sync issues.

Add a new bookmark (FFOX or Chrome)
Error message.

I've tried with the new builds of the extension, unfortunately, the same result.
If you would like to review this with my personal bookmarks or system, perhaps we are facing some kind of a conflict, let me know :)

Thanks.

**Comment by nero120** [comment] 2018-09-19 21:59
@rfmsec I've just tried to replicate your issue but I don't get any errors, when I add the new bookmark in FF after five minutes (in v1.4.0 BETA (c) update check is every five minutes) Chrome automatically syncs and the new bookmark appears, no errors. 😖 

I have a couple of questions that might get to the bottom of this if you don't mind:

1. Which versions of Chrome and Firefox are you using?
2. What OS and version?
3. Just to confirm, you are definitely using v1.4.0 BETA (c) on both Chrome and Firefox (double check on the Settings panel)?
4. If you create a new profile in Chrome (so you are starting with 0 bookmarks) and follow your steps above, do you still get errors?
5. Are you able to paste the error messages logged here?
  a. On Chrome, browse to `chrome://extensions/`, under xBrowserSync click on the `background.html` link, open the console tab and you should see error messages, just right click and save as.
  b. On Firefox, browse to `about:addons`, click on the cog > Debug Add-ons, scroll down to xBrowserSync and click on `Debug`. You can copy and paste the messages direct from the console.
6. It could be something to do with your existing bookmarks, if you are willing to share the xBrowserSync back up file with me for debugging then that would be very helpful! Rather than posting here you can mail it to admin@xbrowsersync.org. 🙏

**Comment by rfmsec** [comment] 2018-09-20 06:52
1. Chrome Version 69.0.3497.100 (Official Build) (64-bit)
Firefox 56.0.2 (64-bit)
2. Windows 10 Build 17134.165
3. I am using the 1.4.0 Beta extensions with the regular API - api xbrowsersync org
4. I will try to create a new profile with no bookmarks and let you know.
5. Coming in the next comment :)
6. Sent.

**Comment by rfmsec** [comment] 2018-09-20 06:56
api.xbrowsersync.org/bookmarks/56349d4af57a48f0a8a8e30b3e0c2cbf/lastUpdated:1 Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
background.min.js:1305 xBrowserSync.App.Background.handleAlarm: undefined
logMessage @ background.min.js:1305
api.xbrowsersync.org/bookmarks/56349d4af57a48f0a8a8e30b3e0c2cbf/lastUpdated:1 Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
background.min.js:1305 xBrowserSync.App.Background.handleAlarm: undefined
logMessage @ background.min.js:1305
background.min.js:1305 xBrowserSync.App.Background.syncBookmarks: Error syncing bookmarks; undefined
logMessage @ background.min.js:1305
(anonymous) @ background.min.js:3509
(anonymous) @ background.min.js:138
$digest @ background.min.js:149
(anonymous) @ background.min.js:152
e @ background.min.js:49
(anonymous) @ background.min.js:51
setTimeout (async)
h.defer @ background.min.js:51
$evalAsync @ background.min.js:152
(anonymous) @ background.min.js:135
k @ background.min.js:137
l @ background.min.js:138
h @ background.min.js:138
(anonymous) @ background.min.js:140
(anonymous) @ background.min.js:3250
safeCallbackApply @ extensions::uncaught_exception_handler:27
handleResponse @ extensions::sendRequest:67
background.min.js:1310 xBrowserSync.App.Background.syncBookmarks: syncData: {"type":1,"changeInfo":{"type":1,"data":["3608",{"dateAdded":1537426195015,"id":"3608","index":11,"parentId":"2","title":"io.netgarage.org","url":"https://io.netgarage.org/","tags":null}]},"deferred":{"promise":{"$$state":{"status":2,"value":{"code":10111},"processScheduled":false,"pur":true}}}}
background.min.js:1305 xBrowserSync.App.Background.createBookmark: undefined
logMessage @ background.min.js:1305
(anonymous) @ background.min.js:3357
(anonymous) @ background.min.js:138
$digest @ background.min.js:149
(anonymous) @ background.min.js:152
e @ background.min.js:49
(anonymous) @ background.min.js:51
setTimeout (async)
h.defer @ background.min.js:51
$evalAsync @ background.min.js:152
(anonymous) @ background.min.js:135
k @ background.min.js:137
l @ background.min.js:138
h @ background.min.js:138
(anonymous) @ background.min.js:140
(anonymous) @ background.min.js:3250
safeCallbackApply @ extensions::uncaught_exception_handler:27
handleResponse @ extensions::sendRequest:67

**Comment by nero120** [comment] 2018-09-20 07:31
Thanks @rfmsec, that's useful.

First off all, it looks like you might be on an older version of the beta. The current version will say `1.4.0 BETA (c)` in Settings > About.

Could you just confirm that you're using this version on both browsers for me?

**Comment by rfmsec** [comment] 2018-09-20 07:35
Chrome:
![image](https://user-images.githubusercontent.com/43323904/45802890-c2a2ec00-bcc0-11e8-802c-d955424c1cbd.png)

FFOX:
![image](https://user-images.githubusercontent.com/43323904/45802968-f1b95d80-bcc0-11e8-8ae0-799f15d68450.png)

**Comment by nero120** [comment] 2018-09-20 08:42
From the log it looks like one of the container folders are being modified, which would be the reason you saw this alert:

![image](https://user-images.githubusercontent.com/4236238/45806524-2f19ed00-bcb9-11e8-983c-c1962db935f1.png)

Are you modifying any folder in `Other Bookmarks` named `[xbs] ...`?

**Comment by rfmsec** [comment] 2018-09-20 08:44
No.

The moment I click on the star icon to add a bookmark, regardless of the last folder I added a bookmark to, I receive this message,

**Comment by nero120** [comment] 2018-09-20 08:49
> 3. I am using the 1.4.0 Beta extensions with the regular API - api xbrowsersync org

Ah, you cannot use [api.xbrowsersync.org](https://api.xbrowsersync.org/) with the BETA, you have to use [api-beta.xbrowsersync.org](https://api-beta.xbrowsersync.org/).

**Comment by rfmsec** [comment] 2018-09-20 08:51
The beta API is deleted every week
I cannot use the regular extension as I will not have firefox

**Comment by nero120** [comment] 2018-09-20 08:53
> The beta API is deleted every week
> I cannot use the regular extension as I will not have firefox

Huh? It is definitely not deleted every week!

**Comment by rfmsec** [comment] 2018-09-20 08:57
> > The beta API is deleted every week
> > I cannot use the regular extension as I will not have firefox
> 
> Huh? It is definitely not deleted every week! Use the BETA extension with api-beta.xbrowsersync.org.

Sorry, got my facts confused :)

![image](https://user-images.githubusercontent.com/43323904/45807461-2aaaff80-bccc-11e8-84d9-a6a5a1b61c36.png)

I am not sure why I had a week in mind.

Can you define long term?

**Comment by nero120** [comment] 2018-09-20 09:06
[api-beta.xbrowsersync.org](https://api-beta.xbrowsersync.org/) was created for testing the v1.4.0 of the app, because I don't want test data polluting live data. When v1.4.0 is released you will be able to backup your beta data and restore it to [api.xbrowsersync.org](https://api.xbrowsersync.org/) for long term use.

**Comment by nero120** [comment] 2018-09-20 09:07
After restoring from the backup you sent me I've managed to replicate your error! Leave it with me and I'll get it fixed, thanks @rfmsec! 😄

**Comment by rfmsec** [comment] 2018-09-20 09:15
After removing the xbs folder which belongs to my old mobile sync I can confirm that everything is working as expected, I no longer receives the mentioned error.

Looks like the cause of the issue has been narrowed a bit :)

**Comment by nero120** [comment] 2018-09-20 10:04
Ok, the issue is being caused by the `[xbs] Mobile` container is stored in your synced data as a folder underneath `[xbs] Other` rather than as a container at the top level. This is then confusing the app which generates the error when attempting to sync a change directly under `Other Bookmarks`. Hence when you delete the `[xbs] Mobile` folder everything works properly.

What should happen when you create a new sync from Firefox, is any mobile bookmarks are added to the `[xbs] Mobile` container at the top level, like so:

```
{
  "xBrowserSync": {
    "bookmarks": [
      {
        "title": "[xbs] Other",
        "children": [
          {
            "title": "Google",
            "url": "https://www.google.co.uk/?gws_rd=ssl",
            "id": 14
          }
        ],
        "id": 19
      },
      {
        "title": "[xbs] Toolbar",
        "children": [
          {
            "title": "Most Visited",
            "url": "place:sort=8&maxResults=10",
            "id": 11
          },
          {
            "title": "Getting Started",
            "url": "https://www.mozilla.org/en-GB/firefox/central/",
            "id": 10
          }
        ],
        "id": 20
      },
      {
        "title": "[xbs] Menu",
        "children": [
          {
            "title": "Recent Tags",
            "url": "place:type=6&sort=14&maxResults=10",
            "id": 12
          },
          {
            "title": "Mozilla Firefox",
            "children": [
              {
                "title": "Help and Tutorials",
                "url": "https://support.mozilla.org/en-GB/products/firefox",
                "id": 6
              },
              {
                "title": "Customise Firefox",
                "url": "https://support.mozilla.org/en-GB/kb/customize-firefox-controls-buttons-and-toolbars?utm_source=firefox-browser&utm_medium=default-bookmarks&utm_campaign=customize",
                "id": 7
              },
              {
                "title": "Get Involved",
                "url": "https://www.mozilla.org/en-GB/contribute/",
                "id": 8
              },
              {
                "title": "About Us",
                "url": "https://www.mozilla.org/en-GB/about/",
                "id": 9
              }
            ],
            "id": 5
          }
        ],
        "id": 21
      },
      {
        "title": "[xbs] Mobile",
        "children": [
          {
            "title": "Mobile",
            "url": "http://m.lse.co.uk/",
            "id": 18
          },
          {
            "title": "Firefox: About your browser",
            "url": "about:firefox",
            "id": 15
          },
          {
            "title": "Firefox: Customise with add-ons",
            "url": "https://addons.mozilla.org/android?utm_source=inproduct&utm_medium=default-bookmarks&utm_campaign=mobileandroid",
            "id": 16
          },
          {
            "title": "Firefox: Support",
            "url": "https://support.mozilla.org/products/mobile?utm_source=inproduct&utm_medium=default-bookmarks&utm_campaign=mobileandroid",
            "id": 17
          }
        ],
        "id": 22
      }
    ]
  }
}
```

You can restore this data to a new sync and you should not have the same issues as before.

The question now is, why did Firefox not sync your mobile bookmarks correctly? Couple of questions if you don't mind:

- When did you create the sync and with which app version?
- Which browser did you originally create the sync on?
- Were the mobile bookmarks present when the sync was created, or were they created (via FF sync) when xBrowserSync was installed and synced?

**Comment by rfmsec** [comment] 2018-09-20 10:45
I think that I have created the sync with the Android mobile app.
I have remained the current structure and have not changed it since creation.

**Comment by rfmsec** [comment] 2018-09-20 10:55
Although I have tried to test this again and the result was different.
The first time I've used the mobile app I had the XBS folder, now I got _xBrowserSync_

So I am not completely sure.

**Comment by nero120** [comment] 2018-09-20 10:57
> The first time I've used the mobile app I had the XBS folder, now I got xBrowserSync

I'm not sure what this means, can you be more specific?

**Comment by rfmsec** [comment] 2018-09-20 11:08
To be honest, I am not sure how the [xbs] mobile became a directory of its own.

I am looking at the structure of the directories in the old version and the sections (toolbar, others etc...) is written with an underscore sign.

Perhaps there was a change between the versions on how the json if formatted?

I have tried the service a long time ago and recently moved back after looking for a replacement for Xmarks...

**Comment by nero120** [comment] 2018-09-20 11:12
Ah I see. Yes you're right there was a change in v1.4.0, I renamed the `_xBrowserSync` container to `[xbs] Unfiled` as it would have to support a number of new containers that Firefox uses and Chrome does not, so the new naming convention makes things a bit clearer.

Perhaps there was some issue along the way but I've just tested FF creating and removing mobile bookmarks whilst xBrowserSync is active and it looks like everything works as expected. Since there's nothing more to do here I'll close this issue, but feel free to re-open if the issue resurfaces.

Many thanks for your help with investigating this @rfmsec 👏

**Closed by nero120** 2018-09-20 11:12 UTC

**Comment by rfmsec** [comment] 2018-09-20 11:18
tyvm for your assistance @nero120 :)
