### ISSUE TITLE
Brave Browser Support

### ISSUE THREAD

**Issue by bhurler1** [xbrowsersync/app#100] opened 2019-05-29 17:15 UTC
Brave is chromium based and has some small quirks. Overall seems to work really well out of the box, only having minor issues such as the search input not automatically focusing. Would be great to add official support.

Thanks!

**Comment by poikilos** [comment] 2019-06-03 19:35
I don't know whether there is "official support" yet, but it seems to work fine after some cross-browser issues were resolved in the betas:
* Sync from Mozilla-based to Chromium-based browsers is fixed with #84 
* Sync from Chromium-based to Mozilla-based browsers is fixed with  #93 (as of 1.5.0beta7)

**Comment by bhurler1** [comment] 2019-06-03 20:05
Correct. @nero120 asked me to make a feature request thread for people to upvote if they wanted it added officially. Then they can see how much the feature is requested by users and discern if they need to allocate the time to fixing the remaining minor issues.

**Comment by nero120** [comment] 2019-06-03 21:05
Until Brave is supported there could well be issues that are not immediately obvious, so if you want to use xBrowserSync with it make sure you take regular back ups just in case! 😄

**Comment by yz778** [comment] 2019-07-21 04:43
I'm using xBrowserSync across Brave (win10), Chrome (win10), and Chromium (linux) -- and happy to report that it's working well.

If you're using Brave, consider turning off Brave's sync. I've had Brave sync on while xBrowserSync was on, and experienced bookmarks duplicated and folders being partially duplicated. If I can reproduce this, i'll file a proper bug report.

**Comment by nero120** [comment] 2019-07-21 07:49
@yz778 xBrowserSync does not support using other sync tools under any circumstances, doing so will always lead to duplication as the native APIs are triggered by those sync tools which then trigger xBrowserSync.

**Comment by yz778** [comment] 2019-07-21 19:53
@nero120, agree and understood. Suggested feature when Brave support is official -- to detect that Brave Sync is on and give a warning.

**Comment by nero120** [comment] 2019-07-21 20:33
@yz778 that's not possible unfortunately as there's no API available for any browser that can determine that. However in v1.5.0 I have included a warning to disable any active syncing tools:

![screenshot](https://user-images.githubusercontent.com/4236238/61596725-278be300-abff-11e9-8c4c-acd959558810.png)

**Comment by indig0F10w** [comment] 2019-08-26 18:26
Greetings, just a quick feedback from a Brave user: xBrowserSync works fine for me on Windows 10 x64, Brave, Firefox and Firefox Developer Edition.

**Comment by nero120** [comment] 2019-08-27 08:46
Thanks @indig0F10w, I've switched to Brave for my main browser and xBrowserSync is working great!

**Comment by sachbearbeiter** [comment] 2019-08-29 13:16
Cool - i will try to use it with Brave too :) Btw. thanks a lot for this wonderful app!

**Comment by lsylvain** [comment] 2019-12-27 19:28
If thus was available for Brave on Android, specifically on Kindle Fire, it would be a great benefit.  I realize that Amazon is at war with Google and has a near closed system (though not nearly as closed as Apple), but I have been able to download APKs for software such as Brave, which is the only really decent browser for the Fire.  Currently there is no way to sync Brave on the Fire as there is no sync option on the Brave settings menu.  Anyway, that's my two bits.

**Comment by gilvandovieira** [comment] 2020-01-02 23:17
@ me when this is implemented!
Waiting for this so bad.

**Comment by Rob4226** [comment] 2020-01-07 07:52
Damn on Win10 xBrowserSync was working perfectly in Brave but now just hours ago, an update of Brave came out and renamed the "Bookmarks bar" folder to "Bookmarks" and what really broke it was they nested the "Other bookmarks" folder under the "Bookmarks" folder.  Now xBrowserSync does not work at all.  Of course, I literally just got down customizing xBrowserSync by adding the date the bookmark was added to the database and then displayed the date added in bookmark search results.  I was spent hours thinking it was something I did even though it was working earlier and I did not make any changes but come to find they changed the bookmark structure. 

Maybe the author @nero120  can point me in the correct direction to update the chrome extension to be work with this new structure?  It seems like it wouldn't be too difficult and actually might even make it cleaner having all the bookmarks start from a single node ("Bookmarks") instead of two, "Bookmark bar" and "Other bookmarks".  I am going to try and do it myself but any insight would be greatly appreciated.  I will post the code if I figure it out.  I'll fork the chrome version and make the hopefully minor changes to the app in order to create a working Brave version again.  Thanks!

**Comment by nero120** [comment] 2020-01-07 11:07
@Rob4226 i was afraid they would do this at some point. It will require a new platform implementation for Brave. This is no easy task even if you are familiar with the xBrowserSync code base and native apis.

I am currently finishing off v1.5.1 for release within the next couple of weeks which will bring the android app up to date. Once that's done i will start work on v1.6.0 which will implement support for remaining mainstream browsers, starting with Brave.

**Comment by Rob4226** [comment] 2020-01-07 16:09
@nero120 Ok thanks for the response!  In that case, I will just wait for v1.6.0  In the meantime, I'll just use a previous release of Brave that works.  I just did that and I can confirm the Chrome extension works again, at least on Windows 10. For anyone else who runs into this problem, the latest release of Brave that fully works with xBrowserSync (up to v1.5.1) is v1.1.23 which can be found here https://github.com/brave/brave-browser/releases/tag/v1.1.23 

After installing a prior version you have to stop Brave from auto-updating by adding an entry to your local hosts file to break the Brave update link i.e.

`0.0.0.0     laptop-updates.brave.com    #prevent Brave from updating to latest version`

Here is a good article to follow for that: https://www.publish0x.com/random/stop-brave-browser-auto-updating-windows-xqwmgo

**Comment by nero120** [comment] 2020-01-07 20:07
Thanks for the info @Rob4226!

**Comment by LaurentOngaro** [comment] 2020-01-16 13:29
@Rob4226 , I'll downgrade my version too, hoping that Brave will make sync extensions work again soon. 
If not, I'll change to another browser, because cross browser syncing is really important for me. 
I will be sad to do that, because brave is really a great alternative on many points

**Comment by ziomik** [comment] 2020-01-19 18:11
Quote..

**Comment by nero120** [comment] 2020-02-21 08:57
Update: Brave have now resolved the [missing other bookmarks](https://github.com/brave/brave-browser/issues/7639) issue, the fix is scheduled to be released in Brave 1.7.x. It is not yet available in the nightly build but once it is I will test it with the current version of xBrowserSync and report back.

**Comment by scudelletti** [comment] 2020-02-23 22:07
Looks like it's working in Brave Nightly Version 1.7.10. 🎉

**Comment by nero120** [comment] 2020-02-24 21:51
> Looks like it's working in Brave Nightly Version 1.7.10. 🎉

Confirmed, thanks @scudelletti!

**Comment by nero120** [comment] 2020-03-02 22:14
FYI all, version 1.7 of Brave (that will include the fix) is scheduled to be publicly released on April 28.

**Comment by rodrigoswz** [comment] 2020-04-14 17:19
Fixed on today's update: "Version 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)"

**Comment by bhurler1** [comment] 2020-04-14 21:07
Awesome. Thanks for the update! I have been keeping tabs on this release waiting to do some testing :)

**Comment by nero120** [comment] 2020-04-15 20:11
> Fixed on today's update: "Version 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)"

@rodrigoswz confirmed, thanks for the heads up!

**Comment by Rob4226** [comment] 2020-04-25 06:47
> > Fixed on today's update: "Version 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)"
> 
> @rodrigoswz confirmed, thanks for the heads up!

Great news! I can finally upgrade from Brave v1.1.23 👍  I've been using that outdated version for months lol

**Closed** 2020-11-01 19:57 UTC
Labels: feature request
