### ISSUE TITLE
The account can't log in

### ISSUE THREAD

**Issue by George1031** [xbrowsersync/app#322] opened 2021-07-13 04:56 UTC
![image](https://user-images.githubusercontent.com/50572421/125392857-7aa56480-e3d9-11eb-84f7-8ba0984b5c1c.png)
The account can't log in. The same account and the same version can be used normally in the Firefox browser
账户无法登录，同样的账户，同样的版本，在火狐浏览器可以正常使用

Desktop browser
Please complete the following information for all affected desktop browsers:

OS: Win10 
Browser chrome 89 
![image](https://user-images.githubusercontent.com/50572421/125392781-5f3a5980-e3d9-11eb-867e-efb18edfdf9b.png)

Version 1.5.2

```
Download the Application log from the Settings panel and paste the contents here.
```

</details>

**Comment by George1031** [comment] 2021-07-20 08:16
The problem still exists. The account is on the plug-in of Chrome browser and cannot log in
You can login on the plug-in by using the Firefox browser

**Comment by nero120** [comment] 2021-07-20 08:17
Can you attach your application log from Chome please?

**Comment by George1031** [comment] 2021-07-20 08:24
> 你能附上Chome的申请日志吗？

[xbs_log_20210720162234.txt](https://github.com/xbrowsersync/app/files/6846623/xbs_log_20210720162234.txt)
This is the log I just tried to log in. Is that ok

**Comment by nero120** [comment] 2021-07-20 08:32
Yes that's great thanks, I see what the issue is:

```
2021-07-07 03:19:41.180	[warn]	Missing container: other bookmarks
```

Sometimes in Chromium browsers, the ids of the root bookmark folders (other bookmarks and bookmarks bar) get changed from the default values. This shouldn't really happen as these values should be constant, and when it does happen sadly it breaks xBrowserSync as it can no longer find the root folders.

There is one relaible fix for this, to [create a new profile](https://mashtips.com/create-new-profile-in-google-chrome/). The new profile will reset the root bookmark folder ids to their defaults, then you can install xBrowserSync and sync to your data as normal.

Give that a try and let me know if it works!

**Comment by George1031** [comment] 2021-07-20 08:42
> 是的，非常感谢，我明白了问题所在：
> 
> ```
> 2021-07-07 03:19:41.180	[warn]	Missing container: other bookmarks
> ```
> 
> 有时在 Chromium 浏览器中，根书签文件夹（其他书签和书签栏）的 id 会从默认值更改。这不应该真的发生，因为这些值应该是恒定的，当它不幸发生时，它会破坏 xBrowserSync，因为它无法再找到根文件夹。
> 
> 对此有一个可靠的解决方法，即[创建一个新的配置文件](https://mashtips.com/create-new-profile-in-google-chrome/)。新配置文件会将根书签文件夹 ID 重置为其默认值，然后您可以正常安装 xBrowserSync 并同步到您的数据。
> 
> 试一试，让我知道它是否有效！

Thank you very much. The problem that bothered me for two weeks has finally been solved. I think other people should also encounter this situation. I don't know if it is the problem of Chrome browser, but I have logged in successfully. Thank you again for your reply and solution

**Comment by nero120** [comment] 2021-07-20 08:45
Glad to hear it! I don't know what causes it but the chrome devs are silent about it, whether this is a browser bug or not I don't know. However I think they should add named functions to the Web Extension API to retrieve root folder ids, fat chance of that happening though! It's a fairly rare case but sadly one we'll have to live with I think.

**Closed by nero120** 2021-07-20 08:45 UTC
