### ISSUE TITLE
Search does not provide expected results

### ISSUE THREAD

**Issue by Shadowpheonix** [xBrowserSync/App#14] opened 2018-04-16 21:57 UTC
### Steps to reproduce
1.  Add bookmarks with names like the following "Bookmark One", "Book Mark Two", "ThirdBookmark".
2.  Search for "mark".
3.  Search for "*mark".

### Expected behaviour
All three book marks should be returned as matches by at least one of the searches above.

### Actual behaviour
Searching for "mark" finds only "Book Mark Two".
Searching for "*mark" reports no bookmarks found.

### Client app information
**App Platform:** (Chrome, Firefox, iOS, etc) 
Tested with Chrome on Windows 10, and with the Android app.

**App Platform Version:** 
1.3.1

#### Other info
```
It appears the search only looks for words beginning with rather than containing the entered text, and does not support wildcards.
```

**Comment by nero120** [comment] 2018-04-17 10:00
Hi @Shadowpheonix, this is actually intended behaviour. I wanted xBrowserSync's bookmark search to be powerful yet intuitive, and to return only the most relevant bookmarks when I entered a query in the search bar. When I initially implemented partial word matches, most of the results returned were not what I was looking for, so I decided to limit partial matches to the beginnings of words only.

For example, if `chumbawumba` is a word in the bookmark title or description, or a tag, then searching for `chumba` will return the bookmark (and if it's a tag you'll get autocompletion). However, searching for `wumba` will not return the bookmark. If I wanted the bookmark to be returned for that search query then I can add a tag `wumba` to the bookmark.

I realise this approach may seem less powerful, but I believe it really does cut down on the amount of non-relevant results, and using tags can help the user tune the results.

This approach also gets around the need to order search results by popularity/relevance which I think would be necessary if returning many partial matches. That might mean needing to collect "usage" data for bookmarks which is not great from a privacy perspective but also means sync data would be used to collect these metrics as well as storing the actual bookmarks.

**Comment by Shadowpheonix** [comment] 2018-04-20 17:54
With `chumbawumba` as a bookmark title, searching for `wumba` behaving as you described seems perfectly reasonable to me.  However, I had expected using a wildcard (IE: `*wumba`) to override that and match words containing the search phrase.  I was extremely surprised (and disappointed) when I discovered that was not the case.

I am also extremely (and unpleasantly) surprised to learn that the search does not match against the URL itself.

I do not really like the idea of having to use tags for this since the browser itself does not support them, which means I would have to spend several hours finding each bookmark in my browser's menu to get the title, then searching for that in XBrowserSync to be able to add the appropriate tags.  This is even more undesirable when taking into consideration this entry in the [XBrowserSync FAQs](https://www.xbrowsersync.org/#faqs)...
>**I added lots of descriptions and tags to my bookmarks, but I’ve just created a new sync and now they are all gone! What happened?**
Bookmark descriptions and tags are not supported by most browsers, xBrowserSync maintains this additional metadata separately. When you create a new sync, xBrowserSync reads the existing bookmark data directly from the browser which will not include any descriptions or tags you might have added to a previous sync. If you have a back up of your previously synced data, restore the backup after creating a new sync and your descriptions and tags will be restored.

I would therefore like to change this bug report to a feature request, asking for wildcard support when searching, and to have the search expanded to also include URLs.
Requiring some sort of modifier in the search to enable URL inclusion would be fine (IE: `~MyURLText` or `InURL:MyUrlText` or similar).

**Comment by nero120** [comment] 2018-04-20 18:11
xBrowserSync *does* match urls! Start typing a url (e.g. "www.github.com") and just like with keywords you'll get autocompletion and any bookmarks whose url begins with what you have typed will be returned.

-------- Original Message --------

**Comment by nero120** [comment] 2018-06-11 10:14
I'm going to close this as search is working as intended. Personally I like the way that search works (obviously!) and I haven't had any other complaints related to search, but if you'd like to create a new issue for a feature request to tweak the way search works do feel free to create it, as with the other feature requests I can then gauge how much demand there is for it by the upvotes on the issue.

**Closed by nero120** 2018-06-11 10:14 UTC

**Comment by sanjeevgopal** [comment] 2019-01-22 05:44
I find that the search is not matching the URL as mentioned above.

**Example:**
Title: The Elastic Beanstalk Command Line Interface (awsebcli)
URL: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3.html

I'm able to search with words from the title, but not from the URL. For instance, a search for *latest* does not match the above.

Also, with the title, I need to type the *(* to find *(awseb*.

**Comment by graphixillusion** [comment] 2020-05-24 11:55
@nero120 
with this approach it will be difficult to search some type of bookmarks, the github's ones for example. Many github projects follows this schema for the address: **github.com/username/project**. The problem is that it's easier to remember the project name rather than the user one. In this particular example, if i start to search using the word "**project**", the search recognizes indeed the word suggesting an autocompletion in the search bar but no bookmark is displayed. For make the search actually works, i need to type **github.com/username/project**. As already suggested, i think it would be better to implement something like this:
- **project*** or ***project*** 
to temporary override the default search mode. What do you think about it?

**Comment by nero120** [comment] 2020-05-24 14:30
@graphixillusion I hear what you're saying, I also have many github project pages bookmarked. However, the current functionality makes sense what you consider that you are actually searching for a partial url fragment (project), which is only really useful in limited circumstances, such with github urls.

Searching for partial url fragments leads to many non-relevant search results and the key to xBrowserSync improving your productivity is to ensure that search only brings back relevant results. Now, if the desired results are not being displayed for a particular query then that is exactly the usecase for tags - in your case simply add a tag `project` to the `github.com/username/project` bookmark and it will not only bring back the search result for your query but will also ensure autocomplete if you enter "project" into the search bar.

Interestingly, your post has alerted me to a bug - you were seeing autocompletion for when you entered "project" but it returned no results. This is because when calculating autocompletion bookmark title values are split by word, but not when the actual search is performed. I'll fix this inconsistency for the next release. This may also resolve your issue without requiring you to add a tag as long as the title for the `github.com/username/project` bookmark is "username/project" (which I believe is the default for github projects anyway).
