### ISSUE TITLE
Extension stuck forever when syncing chrome URLs

### ISSUE THREAD

**Issue by Tansc161** [xbrowsersync/app#68] opened 2019-01-09 16:45 UTC
### Steps to reproduce
1. Create a bookmark that points to a chrome URL and put it to the first place. (eg chrome://bookmarks)
2. Create a sync or backup.
3. Sync this on another browser like Firefox. (I only tested on firefox)

### Expected behaviour
It should either skip it or sync using whatever method that work.

### Actual behaviour
It just trying to sync for that bookmark and keep getting `Invalid_bookmark` error and loop. Takes forever to sync.

### Client app information
**App Platform:** 
Chrome (Origin) & Firefox (Synced)
**App Platform Version:** 
1.4.0
#### Debug log
```
    INFO: Sync data: {"type":2,"command":1,"deferred":{"promise":{"$$state":{"status":2,"value":{},"processScheduled":false,"pur":true}}}}
    ERROR: Error: Invalid bookmark: {"title":"书签","type":1,"url":"chrome://bookmarks/","index":0,"parentGuid":"toolbar_____"}
    INFO: createLocalBookmark: {"index":0,"parentId":"toolbar_____","title":"书签","url":"chrome://bookmarks/"}
    INFO: Sync data: {"type":2,"command":1,"deferred":{"promise":{"$$state":{"status":2,"value":{},"processScheduled":false,"pur":true}}}}
    ERROR: Error: Invalid bookmark: {"title":"书签","type":1,"url":"chrome://bookmarks/","index":0,"parentGuid":"toolbar_____"}
    INFO: createLocalBookmark: {"index":0,"parentId":"toolbar_____","title":"书签","url":"chrome://bookmarks/"}

```

**Comment by nero120** [comment] 2019-01-09 17:17
Hi @Tansc161, this is a duplicate of #58 which will be fixed for the next version.

It's happening because you have some bookmarks with the url starting `chrome://`, which Firefox doesn't support. For now, you can remove these bookmarks and the sync should succeed. You can then add them back once v1.4.1 is released.

**Closed by nero120** 2019-01-09 17:17 UTC

**Comment by Tansc161** [comment] 2019-01-09 17:37
Oh didn't notice this is a dupe, mb.
For now I made a temp fix by changing the `chrome://` protocol to `about:`, which firefox support it so the sync can complete.
Anyway, I am expecting the coming version that fixes this completely, thanks for your response.
