### ISSUE TITLE
existing sync-id stalls

### ISSUE THREAD

**Issue by swestlake** [xbrowsersync/app#69] opened 2019-01-09 20:26 UTC
hi again nero120, 
 I tried to use Firefox again today (very new setup on a linux desktop), and attempting to connect to an existing sync-id causes the "Working on it" window to wait forever.

I am doing the exact same procedure on my additional setups from the 2nd webbrowser and up (of adding an existing sync-id, instead of trying to create a new one) 

Here are the webbrowsers I have been testing xbrowsersync. All 3 web browsers are from the same machine (on a debian 64-bit linux)

Create 1 sync-id with chromium, followed by 2) 3) and 4) in using the same sync-id 

So basically 3 web browsers and demonstrating that no problem with the playstore plugin on Android counting as a four testing client...
1) Created a new sync-id with chromium (I am using a private web server running v1.4.1.beta2)
2) Added the same sync-id on my Android (thanks) . Perfecto no problem here as well.
3) Added the same sync-id on Chrome.. Works here.

and then ultimately
4) Firefox.  doesn't pass "Working on it..." 

I tried Firefox couple of times again today, and it's exactly the same issue as yesterday.. so I'm pretty sure there is something wrong going on.  it's an official build by the distro here with debian linux (using 60.4.0esr-1~deb9u1).. so it must be quality-ready to work for any plugin... 

(note: the latest upstream is version 62 and I can always try this from upstream later and see if that helps, I can report back on this if I see a difference)

Basically when I test the plugin over again, I just remove the plugin entirely, close the browser, and restart again... and every time I wait for "Working on it", it just waits forever.. The connection status in the plugin says "online", so I know there is no network issue..  

I can click outside the wait window and it closes. The plugin icon in Firefox's top-right corner is not green, so it does not retain the login credentials and the greyed icon tells me the sync has failed...

I will try that xbrowser debug feature later and see if I can dig something from it.

After I attempted to connect Firefox with the same sync-id, the bookmarks (from what I can tell) started populating up to about 100.. it went just about 140 this time, yesterday it went to 97... 

I'm looking at Bookmarks/org , and on the other browsers the number of bookmarks item counts to 1383 bookmarks.. Maybe it's the number of bookmarks, but I have already synced chrome without issue(original sync-id was created with chromium)

So the same problem with trying to sync with the same sync-id on Firefox, it waits forever after about the 100th bookmark item that gets partially synced and it just keeps waiting..

I found another thing here, 
A New sync-id with Firefox:
  I can connect to the api server with a brand new sync-id.  It connects and the plugin icon remains green after authenticating, however the path of "Bookmarks/org" remains populated with bookmarks.. so clearly xbrowsersync is not clearing out all the bookmarks...   

thanks

**Comment by nero120** [comment] 2019-01-10 09:14
@swestlake sounds like it could be a similar issue to #58. As you created the sync with chromium, do you have any local bookmarks with url starting with `chrome://`, if so it will currently cause your attempt to enable that sync ID on Firefox to fail.

> I can connect to the api server with a brand new sync-id. It connects and the plugin icon remains green after authenticating, however the path of "Bookmarks/org" remains populated with bookmarks.. so clearly xbrowsersync is not clearing out all the bookmarks...

To clarify, when creating a new sync it should not clear down your local bookmarks, only when syncing to an existing ID, so that is expected behaviour.

**Comment by swestlake** [comment] 2019-01-10 20:20
As a matter of fact I very well do! I use chrome:// entries in my bookmarks, but they suit a particular purpose for the few times that I need them. I just bothered to look again at different url schemes in firefox and chrome and it is possible to also have bookmarks starting with "mailto://abc@abc.com" and "file://" ..

**Comment by swestlake** [comment] 2019-01-10 20:30
effectively I would have zero problem if you revoke the ability to sync non-http/s things, as I can definitely see many problems.

**Comment by nero120** [comment] 2019-01-14 06:47
@swestlake that would likely be the reason why your Firefox sync fails. I'll close this issue but keep an eye on #58, this will be fixed for the next release.

I wouldn't want to restrict bookmarks to only http(s) as there are many different protocols that one might want to bookmark.

**Closed by nero120** 2019-01-14 06:47 UTC
