### ISSUE TITLE
Ability to delete bookmark folders

### ISSUE THREAD

**Issue by sepsol** [xbrowsersync/app#327] opened 2021-08-07 21:50 UTC
**Is your feature request related to a problem?**
A clear and concise description of what the problem is:
I was testing the extension and I created a folder which I'm not able to delete anymore.

**Tell us about your idea**
Use screenshots and links to help illustrate if relevant:
N/A

**Comment by nero120** [comment] 2021-11-29 20:53
Duplicate of #141.

**Closed by nero120** 2021-11-29 20:53 UTC
